name: Build & Deploy
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /home/nodejs/test-emoteracer/emoteracer.xyz
            git pull
            sudo -u nodejs pm2 
            echo 'Deployment Complete'
